added switch_terminals configuration option
jscheffner/vscode-workspace-terminals pull request #1
Opened 2019-11-11 10:30 UTC by valerino

hi, i found your extension which perfectly suit my needs!!!
since i frequently use multi root workspaces, and i also need to switch terminals to each workspace folder, i added this option to your extension.

2019-11-12 13:15 UTC, jscheffner commented
Hey, thanks for the PR, that's a great idea. I just need to find the time to have a closer look at your code, so I might need some days.

2019-11-13 19:35 UTC, jscheffner requested changes

2019-11-13 19:35 UTC, jscheffner commented on package.json
> +				"workspace-terminals.switch_terminals": {
Since the VS Code settings use camelCase I would like to do the same, so I'd prefer `switchTerminals` .

2019-11-13 19:35 UTC, jscheffner commented on src/extension.ts
> +  if (folders != undefined) {
Checking if the path includes the terminal name should work in most cases but can cause some issues in other cases. You can use `workspace.getWorkspaceFolder(e.document.uri)` to get the workspace folder and compare its name with the names of the terminals.

2019-11-13 19:35 UTC, jscheffner commented on src/extension.ts
> +          if (t.name == f.name) {
Please always use `===` instead of `==`.

2019-11-13 19:35 UTC, jscheffner commented on src/extension.ts
> +  if (folders != undefined) {
Please use `!==` instead of `!=`

2019-11-13 19:40 UTC, jscheffner commented
I made some change requests, hope that's okay. If you have questions or want me to make those changes, just say so.

2019-11-14 13:25 UTC, valerino reviewed
hi! sure, your changes makes sense :) sorry but it's the first time i use js and node. you can go on with the changes!

2019-11-14 18:28 UTC, merged

2019-11-14 18:28 UTC, jscheffner commented
Further development will happen on branch **ft/switch-terminals**. Thanks for your contribution.